DROP TABLE EVENT;

CREATE TABLE EVENT
(
  ID   SERIAL,
  NAME VARCHAR(128) UNIQUE NOT NULL,
  PRIMARY KEY (ID)
);

DROP TABLE METRIC;

CREATE TABLE METRIC
(
  ID              SERIAL,
  EVENT_ID        INT,
  VALUE           BIGINT,
  PARAMETERS      VARCHAR(1024),
  EVENT_TIMESTAMP TIMESTAMP,
  PRIMARY KEY (ID),
  FOREIGN KEY (EVENT_ID) REFERENCES EVENT (ID)
);

INSERT INTO EVENT (NAME)
VALUES ('Test name');

INSERT INTO EVENT (NAME) VALUES ('Test name sss') ON CONFLICT (NAME) DO NOTHING;

INSERT INTO METRIC (EVENT_ID, VALUE, PARAMETERS, EVENT_TIMESTAMP)
VALUES (1, 1, 'SomeParams', '2016-06-22 19:10:25-07');

SELECT M.ID, E.NAME, M.VALUE, M.PARAMETERS, M.EVENT_TIMESTAMP
FROM METRIC AS M
       LEFT JOIN EVENT E on M.EVENT_ID = E.ID